---
title: "Lab 5"
author: "Josh Rowe"
format: html
editor: visual
---

## Setup

```{r setup}
#| warning: false
#| message: false

library(here)
library(tidyverse)
library(viridis)

```

## Revisiting Lab 2

```{r}
#| warning: false
#| message: false


surveys <- read_csv(here("Lab Assignments", "Lab 2", "surveys.csv"))


surveys <- surveys |> 
  mutate(species = as.factor(species))


ggplot(data = surveys, mapping = aes(y = fct_reorder(.f = species, 
                                                     .x = weight,
                                                     .fun = median),
                                     x = weight)) + 
  geom_jitter(color = 'tomato', alpha = 0.05) +
  geom_boxplot(outlier.shape = NA) + 
  labs(x = "Weight [g]", 
       y = NULL, 
       title = "Species", 
       title.position = "plot",
       legend = NULL) + 
  theme(plot.title.position = "plot")


```

## Time-Series Plot

```{r}
#| warning: false
#| message: false

surveys <- surveys |> 
  mutate(date = as.Date(date))

# Question 1
ggplot(data = surveys, mapping = aes(x = date, y = weight)) + 
  geom_point(mapping = aes(color = genus)) + 
  scale_colour_viridis_d(aesthetics = "color", option = "C", end = 0.9) + 
  labs(x = "Date", y = NULL, title = "Question 1", subtitle = "Weight [g]") + 
  theme(plot.title.position = "plot")

# Question 2
mean_weights <- surveys |> 
  mutate(year = as.factor(year),
         Genus = as.factor(genus)) |> 
  group_by(Genus, year) |> 
  summarize(weight = mean(weight))

ggplot(data = mean_weights, mapping = aes(x = weight, y = year)) + 
  geom_point(mapping = aes(color = Genus)) + 
  scale_colour_viridis_d(aesthetics = "color", option = "C", end = 0.9) + 
  labs(x = "Weight [g]", y = NULL, title = "Question 2", subtitle = "Date") + 
  theme(plot.title.position = "plot")

# Question 3
ggplot(data = mean_weights, mapping = aes(x = weight, y = year)) + 
  geom_point(mapping = aes(color = fct_reorder(.f = Genus,
                                               .x = weight,
                                               .fun = mean))) + 
  scale_colour_viridis_d(aesthetics = "color", option = "C", end = 0.9) + 
  labs(x = "Weight [g]", y = NULL, title = "Question 3", subtitle = "Date") + 
  theme(plot.title.position = "plot")

# Question 4
ggplot(data = mean_weights, mapping = aes(x = weight, y = year)) + 
  geom_point(mapping = aes(color = fct_reorder(.f = Genus,
                                               .x = weight,
                                               .fun = mean))) + 
  scale_colour_viridis_d(aesthetics = "color", option = "C", end = 0.9) + 
  labs(x = "Weight [g]", y = NULL, title = "Question 4", subtitle = "Date",
       color = "Genus") + 
  theme(plot.title.position = "plot")


```

## Captures of the Week

```{r}
#| warning: false
#| message: false

captures <- surveys |> 
  mutate(day_of_week = as.factor(day_of_week)) |> 
  group_by(day_of_week) |> 
  summarize(captures = n()) |> 
  filter(is.na(day_of_week) == FALSE)

# Question 1
ggplot(data = captures, mapping = aes(x = day_of_week, y = captures)) + 
  geom_point(color = "navy", size = 2) + 
  labs(x = "Day of the Week", y = NULL, title = "Question 1",
       subtitle = "Number of Rodents Caputred") + 
  theme(plot.title.position = "plot")

# Question 2
ggplot(data = captures, mapping = aes(x = fct_relevel(.f = day_of_week,
                                                      "Sun", "Mon", "Tue",
                                                      "Wed", "Thu", "Fri",
                                                      "Sat"),
                                      y = captures)) + 
  geom_point(color = "navy", size = 2) + 
  labs(x = "Day of the Week", y = NULL, title = "Question 2",
       subtitle = "Number of Rodents Caputred") + 
  theme(plot.title.position = "plot")

# Question 3
captures <- captures |> 
  mutate(day_of_week = fct_collapse(day_of_week,
                                    "Weekend" = c("Sat", "Sun"), 
                                    "Weekday" = c("Mon", "Tue", "Wed", 
                                                  "Thu", "Fri")))

ggplot(data = captures, mapping = aes(x = day_of_week,
                                      y = captures)) + 
  geom_point(color = "navy", size = 2) + 
  labs(x = "Day of the Week", y = NULL, title = "Question 3",
       subtitle = "Number of Rodents Caputred") + 
  theme(plot.title.position = "plot")

```
