---
q---
title: "Week 4 Preview"
author: "Joshua Rowe"
format:
  html: 
    code-fold: true
editor: visual
---

## Initialize

```{r}

#| warning: FALSE
#| message: FALSE

library(tidyverse)


```

## Cereals Data

```{r}

cereals_data <- read_csv(here::here("supporting_artifacts", "continued_learning",
                                    "Data", "cereal.csv"))

cereals_long <- cereals_data |> 
  pivot_longer(c(protein, fat, fiber), 
               names_to = "Nutrient", values_to = "Amount") |> 
  select(name, Nutrient, Amount)


```

## Practice with Joins

```{r}

# Creating the datasets

prof_info <- data.frame(
  professor = 
    c("Bodwin", "Glanz", "Carlton", "Sun", "Theobold"),
  undergrad_school = 
    c("Harvard", "Cal Poly", "Berkeley", "Harvard", "Colorado Mesa University"),
  grad_school = 
    c("UNC", "Boston University", "UCLA", "Stanford", "Montana State University")
)

prof_course <- data.frame(
  professor = c("Bodwin", "Glanz", "Carlton", "Theobold"),
  Stat_331 = c(TRUE, TRUE, TRUE, TRUE),
  Stat_330 = c(FALSE, TRUE, TRUE, FALSE),
  Stat_431 = c(TRUE, TRUE, FALSE, TRUE)
)

course_info <- data.frame(
  course = c("Stat_331", "Stat_330", "Stat_431"),
  num_sections = c(8, 3, 1)
)

# Performing Join Operations on the Datasets

a <- right_join(prof_info, prof_course, by = "professor")


b <- left_join(prof_info, prof_course, by = "professor")


prof_course_long <- prof_course |> 
  pivot_longer(c(Stat_331, Stat_330, Stat_431), names_to = "course", values_to = "can_teach")

c <- left_join(prof_course_long, course_info, by = "course")

```
